FROM python:3.11-slim

RUN pip install \
    numpy \
    pandas \
    scikit-learn \
    matplotlib \
    seaborn \
    requests \
    pillow \
    scipy \
    statsmodels

WORKDIR /code

CMD ["python", "solution.py"]